[package]
name = "minty-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
minty = { path = "../minty", features = ["http"] }
owo-colors = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true, features = ["rt"] }

[[bin]]
name = "minty"
path = "src/main.rs"
