[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
chrono = "0.4"
futures = "0.3"
serde = "1"
sqlx = { version = "0.7", features = [
    "chrono",
    "macros",
    "postgres",
    "runtime-tokio",
    "uuid",
] }
thiserror = "1"
url = "2"
uuid = "1"

[workspace.dependencies.pgtools]
git = "https://git.aurora.aur/genya/pgtools.git"

[workspace.dependencies.sqlx-helper-macros]
git = "https://git.aurora.aur/genya/sqlx-helper-macros.git"
