[package]
name = "mintyd"
version = "0.5.3"
edition = "2021"

[dependencies]
axum = { workspace = true }
axum-extra = { workspace = true, features = ["async-read-body", "query"] }
axum-unix = { workspace = true, features = ["serde"] }
chrono = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
crossterm = { workspace = true }
dmon = { workspace = true }
log = { workspace = true, features = ["serde"] }
minty = { path = "../minty", features = ["http"] }
minty-core = { path = "../minty-core" }
ratatui = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_yaml = { workspace = true }
sync_wrapper = { workspace = true, features = ["futures"] }
timber = { workspace = true, features = ["serde"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
tokio-util = { workspace = true, features = ["io"] }
