[package]
name = "mintyd"
version = "0.5.3"
edition = "2021"
build = "build.rs"

[dependencies]
axum-unix = { workspace = true, features = ["serde"] }
clap = { workspace = true, features = ["derive", "env"] }
log = { workspace = true, features = ["serde"] }
minty-core = { path = "../minty-core" }
serde = { workspace = true, features = ["derive"] }
shadow-rs = { workspace = true }
timber = { workspace = true, features = ["serde"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
serde_yaml = { workspace = true }

[build-dependencies]
shadow-rs = { workspace = true }
