[package]
name = "mintyd"
version = "0.5.3"
edition = "2021"
build = "build.rs"

[dependencies]
axum = { workspace = true }
axum-extra = { workspace = true, features = ["query"] }
axum-unix = { workspace = true, features = ["serde"] }
clap = { workspace = true, features = ["derive", "env"] }
dmon = { workspace = true }
log = { workspace = true, features = ["serde"] }
minty = { path = "../minty", features = ["http"] }
minty-core = { path = "../minty-core" }
serde = { workspace = true, features = ["derive"] }
serde_yaml = { workspace = true }
shadow-rs = { workspace = true }
timber = { workspace = true, features = ["serde"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[build-dependencies]
shadow-rs = { workspace = true }
