[package]
name = "minty-core"
version = "0.5.3"
edition = "2021"

[dependencies]
elasticsearch = { workspace = true }
futures = { workspace = true }
minty = { path = "../minty" }
pgtools = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sqlx = { workspace = true }
sqlx-helper-macros = { workspace = true }
thiserror = { workspace = true }
