[package]
name = "minty"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }
url = { workspace = true }
uuid = { workspace = true }

# HTTP dependencies
mime = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true, features = ["json"] }

# minty CLI dependencies
clap = { workspace = true, features = ["derive", "env"], optional = true }
tokio = { workspace = true, features = ["rt"], optional = true }
serde_json = { workspace = true, optional = true }
serde_yaml = { workspace = true, optional = true }

[features]
cli = ["http", "dep:clap", "dep:serde_json", "dep:serde_yaml", "dep:tokio"]
http = ["serde", "dep:mime", "dep:reqwest"]
serde = ["dep:serde", "chrono/serde", "url/serde", "uuid/serde"]

[[bin]]
name = "minty"
required-features = ["cli"]
