[package]
name = "minty"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }
url = { workspace = true }
uuid = { workspace = true }

# HTTP dependencies
mime = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true, features = ["json"] }

[features]
http = ["serde", "dep:mime", "dep:reqwest"]
serde = ["dep:serde", "chrono/serde", "url/serde", "uuid/serde"]
